version: 2
updates:
  - package-ecosystem: cargo
    directory: /gateway
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /gateway
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /ha_voice_hermes_gateway
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /ha_voice_hermes_gateway
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
