#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -Eeuo pipefail

ulimit -c 0

exec /usr/bin/env -i \
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  HOME=/root \
  TMPDIR=/tmp \
  /usr/local/bin/gateway-supervisor
